name: Preview Deployment
permissions:
  actions: write
  contents: read
  checks: read
  pull-requests: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - main
      - staging
      - testing
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'outdated_runs'
          paths_ignore: '["**/README.md", "**/ag-guideline.md", "**/docs/**", ".github/**"]'
          cancel_others: 'true'

  changed-packages:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    name: Determine which apps changed
    uses: ./.github/workflows/changed-packages.yaml
  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: [pre_job, changed-packages]
    if: needs.pre_job.outputs.should_skip != 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Prepare Environment
        uses: ./.github/actions/setup-env
        timeout-minutes: 10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Web
        # use always to make all steps will continue to run even if some steps fail
        if: contains(toJson(fromJson(needs.changed-packages.outputs.package_changed).packages), 'web') && always()
        uses: ./.github/actions/preview
        timeout-minutes: 10
        with:
          vercel-token: ${{ secrets.VERCEL_ACCESS_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_WEB_PROJECT_ID }} #Required
          vercel-project-name: 'web'

      - name: Deploy Docs
        if: contains(toJson(fromJson(needs.changed-packages.outputs.package_changed).packages), 'docs') && always()
        uses: ./.github/actions/preview
        timeout-minutes: 10
        with:
          vercel-token: ${{ secrets.VERCEL_ACCESS_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_DOCS_PROJECT_ID }} #Required
          vercel-project-name: 'docs'
